config/routes.rb
Rails.application.routes.draw do
  resources :savings

  resources :drawers do
    resources :savings
  end


  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/drawer.rb
class Drawer < ActiveRecord::Base
  has_many :savings
end

app/models/saving.rb
class Saving < ActiveRecord::Base
  belongs_to :drawer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drawers_controller.rb
class DrawersController < ApplicationController
  before_action :set_drawer, only: [:show, :edit, :update, :destroy]

  # GET /drawers
  # GET /drawers.json
  def index
    @drawers = Drawer.all
  end

  # GET /drawers/1
  # GET /drawers/1.json
  def show
  end

  # GET /drawers/new
  def new
    @drawer = Drawer.new
  end

  # GET /drawers/1/edit
  def edit
  end

  # POST /drawers
  # POST /drawers.json
  def create
    @drawer = Drawer.new(drawer_params)

    respond_to do |format|
      if @drawer.save
        format.html { redirect_to @drawer, notice: 'Drawer was successfully created.' }
        format.json { render :show, status: :created, location: @drawer }
      else
        format.html { render :new }
        format.json { render json: @drawer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drawers/1
  # PATCH/PUT /drawers/1.json
  def update
    respond_to do |format|
      if @drawer.update(drawer_params)
        format.html { redirect_to @drawer, notice: 'Drawer was successfully updated.' }
        format.json { render :show, status: :ok, location: @drawer }
      else
        format.html { render :edit }
        format.json { render json: @drawer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drawers/1
  # DELETE /drawers/1.json
  def destroy
    @drawer.destroy
    respond_to do |format|
      format.html { redirect_to drawers_url, notice: 'Drawer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drawer
      @drawer = Drawer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drawer_params
      params.require(:drawer).permit(:DrawerTitle, :TargetAmount, :TargetDate)
    end
end

app/controllers/savings_controller.rb
class SavingsController < ApplicationController
  before_action :set_saving, only: [:show, :edit, :update, :destroy]

  # GET /savings
  # GET /savings.json
  def index
    @savings = Saving.all
  end

  # GET /savings/1
  # GET /savings/1.json
  def show
  end

  # GET /savings/new
  def new
    @saving = Saving.new
  end

  # GET /savings/1/edit
  def edit
  end

  # POST /savings
  # POST /savings.json
  def create
    @saving = Saving.new(saving_params)

    respond_to do |format|
      if @saving.save
        format.html { redirect_to @saving, notice: 'Saving was successfully created.' }
        format.json { render :show, status: :created, location: @saving }
      else
        format.html { render :new }
        format.json { render json: @saving.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /savings/1
  # PATCH/PUT /savings/1.json
  def update
    respond_to do |format|
      if @saving.update(saving_params)
        format.html { redirect_to @saving, notice: 'Saving was successfully updated.' }
        format.json { render :show, status: :ok, location: @saving }
      else
        format.html { render :edit }
        format.json { render json: @saving.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /savings/1
  # DELETE /savings/1.json
  def destroy
    @saving.destroy
    respond_to do |format|
      format.html { redirect_to savings_url, notice: 'Saving was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saving
      @saving = Saving.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def saving_params
      params.require(:saving).permit(:DrawerID, :AddedSaving, :AddedDate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drawers_helper.rb
module DrawersHelper
end

app/helpers/savings_helper.rb
module SavingsHelper
end

app/views/drawers/_form.html.erb
<%= form_for(@drawer) do |f| %>
  <% if @drawer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drawer.errors.count, "error") %> prohibited this drawer from being saved:</h2>

      <ul>
      <% @drawer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :DrawerTitle %><br>
    <%= f.text_field :DrawerTitle %>
  </div>
  <div class="field">
    <%= f.label :TargetAmount %><br>
    <%= f.number_field :TargetAmount %>
  </div>
  <div class="field">
    <%= f.label :TargetDate %><br>
    <%= f.date_select :TargetDate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drawers/edit.html.erb
<h1>Editing drawer</h1>

<%= render 'form' %>

<%= link_to 'Show', @drawer %> |
<%= link_to 'Back', drawers_path %>

app/views/drawers/index.html.erb
<h1>Listing drawers</h1>

<table>
  <thead>
    <tr>
      <th>Drawertitle</th>
      <th>Targetamount</th>
      <th>Targetdate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drawers.each do |drawer| %>
      <tr>
        <td><%= drawer.DrawerTitle %></td>
        <td><%= drawer.TargetAmount %></td>
        <td><%= drawer.TargetDate %></td>
        <td><%= link_to 'Show', drawer %></td>
        <td><%= link_to 'Edit', edit_drawer_path(drawer) %></td>
        <td><%= link_to 'Destroy', drawer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Drawer', new_drawer_path %>

app/views/drawers/new.html.erb
<h1>New drawer</h1>

<%= render 'form' %>

<%= link_to 'Back', drawers_path %>

app/views/drawers/show.html.erb
<p id="notice"><%= notice %></p>
<article id="show_drawer_box">
  引き出し
</article>
<p>
  <strong>Drawertitle:</strong>
  <%= @drawer.DrawerTitle %>
</p>

<p>
  <strong>Targetamount:</strong>
  <%= @drawer.TargetAmount %>
</p>

<p>
  <strong>Targetdate:</strong>
  <%= @drawer.TargetDate %>
</p>
<article>
  <%= link_to 'Add Saving', new_drawer_saving_path(@drawer) %>
</article>
<%= link_to 'Edit', edit_drawer_path(@drawer) %> |
<%= link_to 'Back', drawers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SavingsManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/savings/_form.html.erb
<%= form_for(@saving) do |f| %>
  <% if @saving.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@saving.errors.count, "error") %> prohibited this saving from being saved:</h2>

      <ul>
      <% @saving.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :DrawerID %><br>
    <%= f.text_field :DrawerID %>
  </div>
  <div class="field">
    <%= f.label :AddedSaving %><br>
    <%= f.number_field :AddedSaving %>
  </div>
  <div class="field">
    <%= f.label :AddedDate %><br>
    <%= f.date_select :AddedDate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/savings/edit.html.erb
<h1>Editing saving</h1>

<%= render 'form' %>

<%= link_to 'Show', @saving %> |
<%= link_to 'Back', savings_path %>

app/views/savings/index.html.erb
<h1>Listing savings</h1>

<table>
  <thead>
    <tr>
      <th>Drawerid</th>
      <th>Addedsaving</th>
      <th>Addeddate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @savings.each do |saving| %>
      <tr>
        <td><%= saving.DrawerID %></td>
        <td><%= saving.AddedSaving %></td>
        <td><%= saving.AddedDate %></td>
        <td><%= link_to 'Show', saving %></td>
        <td><%= link_to 'Edit', edit_saving_path(saving) %></td>
        <td><%= link_to 'Destroy', saving, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Saving', new_saving_path %>

app/views/savings/new.html.erb
<h1>New saving</h1>

<%= render 'form' %>

<%= link_to 'Back', savings_path %>

app/views/savings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Drawerid:</strong>
  <%= @saving.DrawerID %>
</p>

<p>
  <strong>Addedsaving:</strong>
  <%= @saving.AddedSaving %>
</p>

<p>
  <strong>Addeddate:</strong>
  <%= @saving.AddedDate %>
</p>

<%= link_to 'Edit', edit_saving_path(@saving) %> |
<%= link_to 'Back', savings_path %>